Registration endpoint #6
BuildForSDGCohort2/team-101-backend pull request #18
Opened 2020-09-13 14:25 UTC by captbilard

Created registration endpoint using dj-rest-auth

2020-09-13 19:10 UTC, Damephena requested changes
Kindly make changes. Thanks

2020-09-13 19:10 UTC, Damephena commented on accounts/migrations/0001_initial.py
> +# Generated by Django 3.0 on 2020-09-11 15:16
Which version of Django are you using? Did you install the requirements.txt file?

2020-09-13 19:10 UTC, Damephena commented on accounts/serializers.py
> +
pep8 spacing: Hi, it would be great to have consistent spacing in the file.

2020-09-13 19:10 UTC, Damephena commented on accounts/views.py
pep8 spacing

2020-09-13 19:10 UTC, Damephena commented on accounts/tests.py
pep8 spacing

2020-09-15 20:52 UTC, captbilard commented on accounts/migrations/0001_initial.py
> +# Generated by Django 3.0 on 2020-09-11 15:16
Yea I installed all required packages using the requirements.txt file.

2020-09-15 22:33 UTC, captbilard commented on accounts/tests.py
Done, Kindly review.

2020-09-15 23:42 UTC, Damephena commented on accounts/migrations/0001_initial.py
> +# Generated by Django 3.0 on 2020-09-11 15:16
Okay.

2020-09-16 06:53 UTC, Damephena approved these changes
👍🏽

2020-09-16 06:59 UTC, merged